FROM ubuntu:22.04
ARG DEBIAN_FRONTEND=noninteractive

RUN \
        dpkg --add-architecture i386 && \
        apt-get update && \
        apt-get install -yq sudo build-essential git nano vim\
          python3-yaml libncursesw5 libncursesw5:i386 \
          python3 man bash diffstat gawk chrpath wget cpio \
          texinfo lzop apt-utils bc screen libncurses5-dev locales \
          libc6-dev-i386 doxygen libssl-dev dos2unix xvfb x11-utils \
          g++-multilib libssl-dev:i386 zlib1g-dev:i386 \
          libtool libtool-bin procps python3-distutils pigz socat \
          zstd iproute2 lz4 iputils-ping \
	  git-lfs python3-pip python3-pexpect python3-git python3-jinja2 \
	  xz-utils debianutils libsdl1.2-dev pylint bsdmainutils \
	  libusb-1.0-0 bison flex libegl1-mesa \
	  libgmp-dev libmpc-dev libyaml-dev \
	  lrzsz corkscrew cvs subversion mercurial \
	  nfs-common nfs-kernel-server libarchive-zip-perl \
	  texi2html libxml2-utils iptables \
          curl libtinfo5 net-tools xterm rsync u-boot-tools unzip zip && \
        rm -rf /var/lib/apt-lists/* && \
        echo "dash dash/sh boolean false" | debconf-set-selections && \
        dpkg-reconfigure dash

RUN curl https://storage.googleapis.com/git-repo-downloads/repo > /bin/repo && chmod a+x /bin/repo
RUN sed -i '1s|python[0-9.]*|python3|' /bin/repo

RUN groupadd intins -g 999 && \
    useradd -ms /bin/bash -p intins intins -u 1000 -g 999 && \
    usermod -aG sudo intins && \
    echo "intins:intins" | chpasswd

RUN echo "en_US.UTF-8 UTF-8" > /etc/locale.gen && \
    locale-gen

ENV LANG=en_US.utf8

USER intins
WORKDIR /home/intins

RUN git config --global user.email "nam.dinh@intins.vn" && \
    git config --global user.name "dinhnamuet"

ENV DL_DIR=/home/intins/downloads
ENV SSTATE_DIR=/home/intins/sstate-cache
ENV BB_ENV_PASSTHROUGH_ADDITIONS="DL_DIR SSTATE_DIR"

